added modal window
BogdanRadetskiy/crm-time-tracking pull request #1
Opened 2022-04-06 14:53 UTC by BogdanRadetskiy

2022-04-15 07:18 UTC, MaxLogvyniukFive requested changes

2022-04-15 07:18 UTC, MaxLogvyniukFive commented on crm-client/src/pages/account/UserProject.jsx
> +const UserProject = () => {
Please use function declaration

2022-04-15 07:18 UTC, MaxLogvyniukFive commented on crm-client/src/pages/account/UserProject.jsx
> +                <button className='open-btn' onClick={() => setModalActive(true)}>Project 1</button>
Move onClick from return to function body

2022-04-15 07:18 UTC, MaxLogvyniukFive commented on crm-client/src/pages/account/UserProject.jsx
> +                <button className='open-btn' onClick={() => setModalActive(true)}>Project 2</button>
Create one function and reuse it

2022-04-15 07:18 UTC, MaxLogvyniukFive commented on crm-client/src/pages/account/UserProject.jsx
> +                <button className='open-btn' onClick={() => setModalActive(true)}>Project 3</button>
-

2022-04-22 06:26 UTC, MaxLogvyniukFive requested changes
Need to update crm-server from express to nest.js

2022-04-22 06:26 UTC, MaxLogvyniukFive commented on crm-client/src/pages/modal/Modal.jsx
> +            <div className={active ? "modal__content active" : "modal__content"}onClick={e => e.stopPropagation()}>
Need to add white space "} onClick={e => e.stopPropagation()"

2022-04-22 06:26 UTC, MaxLogvyniukFive commented on crm-client/src/pages/projects/ProjectsInsert.jsx
> +            window.alert(`Project inserted successfully`)
Nice to change all alerts to [react-toastify](https://www.npmjs.com/package/react-toastify)

2022-04-29 06:23 UTC, wrximpreza requested changes

2022-04-29 06:23 UTC, wrximpreza commented on crm-client/src/pages/account/UserProject.jsx
> +            <Modal active={modalActive} setActive={setModalActive}>
<Modal active={modalActive} setActive={setModalActive} />

2022-04-29 06:23 UTC, wrximpreza commented on crm-client/src/pages/account/UserProject.jsx
> +    const [modalActive, setModalActive] = useState(true)
https://usehooks-ts.com/react-hook/use-boolean

2022-04-29 06:23 UTC, wrximpreza commented on crm-client/src/pages/account/UserProject.jsx
> +        <div className='UserProject'>
id='UserProject' or className='user-project'

2022-04-29 06:23 UTC, wrximpreza commented on crm-client/src/pages/modal/Modal.jsx
> +        <div className={active ? "modal active" : "modal"} onClick={() => setActive(false)}>
https://www.npmjs.com/package/classnames

2022-05-09 09:18 UTC, RomanPidlisnychyi approved these changes

2022-05-09 09:29 UTC, merged